app = 'dictator'
primary_region = 'iad'

[[restart]]
  policy = "on-failure"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[env]
  # BOT_TOKEN=
  DB_HOST="db.twohoursonelife.com"
  DB_DB="PROD_2HOL"
  DB_USER="dictator"
  # DB_PASS=

  # BOT_PREFIX=
  # Dev server channels:
  # MOD_ROLE_ID="1067419807030452224"
  # GAME_MOD_ROLE_ID="1108008984633417748"
  # LOG_CHANNEL_ID="678099820778618881"
  # STATS_CHANNEL_ID="744030831391014943"
  # DEBUG_CHANNEL_ID="678099820778618881"
  # SUGGESTION_CHANNEL_ID="1202633042137448528"
  # OC_CHANNEL_ID="1329825120004608032"
  # EXP_CHANNEL_ID="1165131534647439391"
  # VET_CHANNEL_ID="1165131534647439391"

  # OC_GRAPHQL_ENDPOINT=
  # OC_ANALYSIS_PERIOD_MONTHS=
  OC_FORECAST_MONTH_DAY=6

  # PLAYER_LIST_PASSWORD=

  # SENTRY_DSN=
  SENTRY_ENVIRONMENT="prod"
