app = "dictator"
primary_region = "ewr"

[[restart]]
  policy = "on-failure"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[env]
  DB_HOST="db.twohoursonelife.com"
  DB_DB="PROD_2HOL"
  DB_USER="dictator"
  SENTRY_ENVIRONMENT="production"
