name: Test, release and deploy Dictator

on:
  push:
  workflow_dispatch:

jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Run pytest
        run: uv run pytest
        # TODO: See constants.py.
        env:
          BOT_TOKEN: ""
          DB_PASS: ""
          OC_GRAPHQL_KEY: ""
          PLAYER_LIST_PASSWORD: ""


  release:
    runs-on: ubuntu-latest
    if: github.ref_name == 'main'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: twohoursonelife
          SENTRY_PROJECT: dictator
        with:
          environment: prod
